### ISSUE TITLE
Can you make a modification to take accept a Comma Separated List of Application IDs

### ISSUE THREAD

**Issue by hughbrien** [robertvandervoort/AppDynamics-Data-Extractor#1]
Can you make a modification to take accept a Comma Separated List of Application IDs

**Comment by robertvandervoort** [comment]
I have added a multiselect box so you can choose "ALL" or any n number of apps by name instead of using the app id. If you do not connect and use the multiselect, the application id box is still available to use. 

Does the multiselect input address your needs or would you like the application id field to accept a comma separated list?

**Comment by hughbrien** [comment]
This is good.
